In [2]:
# Install libraries
!pip install pandas scikit-learn imbalanced-learn tensorflow

# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
df = pd.read_csv('customer_data.csv')

# Optional: add a fake Churn column for now (0/1 randomly assigned for testing)
import numpy as np
df['Churn'] = np.random.randint(0, 2, df.shape[0])

# Drop customerID
df.drop(columns=['customerID'], inplace=True)

# Convert TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.dropna(inplace=True)  # Drop rows with missing values

# Encode categorical columns
df = pd.get_dummies(df, drop_first=True)

# Define features and target
X = df.drop('Churn', axis=1)
y = df['Churn']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Balance the data
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# 1. Logistic Regression
print("\n--- Logistic Regression ---")
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_res, y_train_res)
y_pred_lr = lr_model.predict(X_test)
print(confusion_matrix(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

# 2. Decision Tree
print("\n--- Decision Tree ---")
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_res, y_train_res)
y_pred_dt = dt_model.predict(X_test)
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

# 3. Neural Network
print("\n--- Neural Network ---")
scaler = StandardScaler()
X_train_res_scaled = scaler.fit_transform(X_train_res)
X_test_scaled = scaler.transform(X_test)

nn_model = Sequential([
    Dense(32, activation='relu', input_shape=(X_train_res_scaled.shape[1],)),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])
nn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
nn_model.fit(X_train_res_scaled, y_train_res, epochs=50, batch_size=10, verbose=0)

# Evaluate NN
loss, accuracy = nn_model.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Neural Network Test Accuracy: {accuracy:.4f}")
y_pred_nn = (nn_model.predict(X_test_scaled) > 0.5).astype(int)
print(confusion_matrix(y_test, y_pred_nn))
print(classification_report(y_test, y_pred_nn))


   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/376.0 MB ? eta -:--:--
   ---------------------------------------- 0.8/376.0 MB 2.4 MB/s eta 0:02:37
   ---------------------------------------- 1.3/376.0 MB 2.5 MB/s eta 0:02:31
   ---------------------------------------- 2.1/376.0 MB 2.7 MB/s eta 0:02:17
   ---------------------------------------- 2.9/376.0 MB 2.9 MB/s eta 0:02:09
   ---------------------------------------- 3.7/376.0 MB 3.1 MB/s eta 0:02:00
    --------------------------------------- 4.7/376.0 MB 3.4 MB/s eta 0:01:51
    --------------------------------------- 5.8/376.0 MB 3.5 MB/s eta 0:01:46
    ------------------------

C:\Users\tirth\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[420 434]
 [438 466]]
              precision    recall  f1-score   support

           0       0.49      0.49      0.49       854
           1       0.52      0.52      0.52       904

    accuracy                           0.50      1758
   macro avg       0.50      0.50      0.50      1758
weighted avg       0.50      0.50      0.50      1758


--- Decision Tree ---
[[422 432]
 [451 453]]
              precision    recall  f1-score   support

           0       0.48      0.49      0.49       854
           1       0.51      0.50      0.51       904

    accuracy                           0.50      1758
   macro avg       0.50      0.50      0.50      1758
weighted avg       0.50      0.50      0.50      1758


--- Neural Network ---


C:\Users\tirth\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Neural Network Test Accuracy: 0.5108
55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
[[482 372]
 [488 416]]
              precision    recall  f1-score   support

           0       0.50      0.56      0.53       854
           1       0.53      0.46      0.49       904

    accuracy                           0.51      1758
   macro avg       0.51      0.51      0.51      1758
weighted avg       0.51      0.51      0.51      1758



In [16]:
# Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load dataset
df = pd.read_csv('customer_data.csv')
df
# Load dataset
# df = pd.read_csv('/content/sample_data/customer_data.csv')

# TEMPORARY: Add fake churn column if not already there
import numpy as np
if 'Churn' not in df.columns:
    df['Churn'] = np.random.randint(0, 2, df.shape[0])

# Drop customerID
df.drop(columns=['customerID'], inplace=True)

# Convert TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.dropna(inplace=True)

# Separate features and target BEFORE one-hot encoding
y = df['Churn']  # Save target column
X = df.drop('Churn', axis=1)  # Drop target from features

# Encode categorical features
X = pd.get_dummies(X, drop_first=True)

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)
